/**
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Response2002
 *
 * @constructor
 */
angular.module('ReleansAPILib')
    .factory('Response2002', ['BaseModel', Response2002Model]);

    function Response2002Model(BaseModel) {
        var Response2002 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.balance = this.getValue(obj.balance);
        };

        Response2002.prototype = new BaseModel();
        Response2002.prototype.constructor = Response2002;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Response2002.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'balance', realName: 'balance' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Response2002.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        Response2002.prototype.getBalance = function () {
            return this.balance;
        };
    
        /**
         * Setter for Balance
         * 
         * @param {int} value 
         */
        Response2002.prototype.setBalance = function (value) {
            this.balance = value;
        };
    
        return Response2002;
    }

}(angular));
