/**
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
	'use strict';

	angular.module('ReleansAPILib', ['angularMoment']);

}(angular));