/**
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('ReleansAPILib')
    .factory('Servers', [ServersModel]);

    function ServersModel() {
        return {
            //TODO: Write general description for this element
            SERVER_1: 'Server 1'
        };
    }

}(angular));
